"""Fail the build when the safety argument has a gap, in either direction.

A requirement with no test is a hole: something was asserted and never checked.
A test claiming a requirement that does not exist is the quieter one, because it
runs, it passes, and it makes the matrix look complete while verifying nothing
that was asked for. One mistyped character is enough.

Both directions are enforced here and `tests/test_traceability_gate.py`
deliberately breaks each of them, because a gate nobody has watched fail is an
assumption rather than a control.

The test-to-requirement link is read by parsing the test files with `ast` rather
than by running them. Parsing cannot be fooled by a marker inside a string or a
comment, and it means the gate works on a suite too broken to collect, which is
exactly when you want to know what is no longer covered.
"""

from __future__ import annotations

import ast
import sys
from collections import defaultdict
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
ANALYSIS = ROOT / "safety" / "hazards.yaml"
TESTS = ROOT / "tests"
REPORT = ROOT / "report" / "traceability.md"

#: The marker a test uses to claim a requirement: @pytest.mark.verifies("SR-01")
MARKER = "verifies"


def load_analysis() -> dict[str, list[dict[str, object]]]:
    return yaml.safe_load(ANALYSIS.read_text())


def claims_in(path: Path) -> dict[str, list[str]]:
    """Requirement ids claimed by each test function in one file."""
    tree = ast.parse(path.read_text(), filename=str(path))
    found: dict[str, list[str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef):
            continue
        for decorator in node.decorator_list:
            if not isinstance(decorator, ast.Call):
                continue
            attribute = decorator.func
            if not isinstance(attribute, ast.Attribute) or attribute.attr != MARKER:
                continue
            for argument in decorator.args:
                if isinstance(argument, ast.Constant) and isinstance(argument.value, str):
                    found.setdefault(node.name, []).append(argument.value)
    return found


def collect_claims(tests: Path) -> dict[str, list[tuple[str, str]]]:
    """requirement id -> [(file, test name)], over every test module."""
    claimed: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for path in sorted(tests.glob("test_*.py")):
        for test, requirements in claims_in(path).items():
            for requirement in requirements:
                claimed[requirement].append((path.name, test))
    return claimed


def build_report(analysis: dict[str, list[dict[str, object]]],
                 claimed: dict[str, list[tuple[str, str]]]) -> str:
    goals = {str(g["id"]): g for g in analysis["goals"]}
    hazards = {str(h["id"]): h for h in analysis["hazards"]}

    lines = [
        "# Requirement to test traceability",
        "",
        "Generated by `scripts/check_traceability.py` from `safety/hazards.yaml`",
        "and the tests themselves. Do not edit by hand.",
        "",
        "Every requirement traces up to a safety goal and a hazard, and down to at",
        "least one test that verifies it. The build fails on a gap in either",
        "direction: a requirement nobody tests is a hole in the argument, and a test",
        "claiming a requirement that does not exist inflates the matrix while",
        "verifying nothing that was asked for.",
        "",
        "## Hazards",
        "",
        "| | Hazard | Harm |",
        "|---|---|---|",
    ]
    for hazard in analysis["hazards"]:
        lines.append(f"| {hazard['id']} | {hazard['text']} | {hazard['harm']} |")

    lines += ["", "## Safety goals", "", "| | Goal | From |", "|---|---|---|"]
    for goal in analysis["goals"]:
        covers = ", ".join(str(h) for h in goal["hazards"])
        lines.append(f"| {goal['id']} | {goal['text']} | {covers} |")

    lines += ["", "## Requirements, and what verifies them", "",
              "| | Requirement | Goal | Hazards | Verified by |", "|---|---|---|---|---|"]
    for requirement in analysis["requirements"]:
        rid = str(requirement["id"])
        goal_id = str(requirement["goal"])
        covers = ", ".join(str(h) for h in goals[goal_id]["hazards"])
        tests = "<br>".join(f"`{test}`" for _, test in claimed.get(rid, []))
        lines.append(
            f"| {rid} | {requirement['text']} | {goal_id} | {covers} | {tests} |")

    lines += ["", "## Coverage", "",
              f"- Hazards: **{len(hazards)}**",
              f"- Safety goals: **{len(goals)}**",
              f"- Requirements: **{len(analysis['requirements'])}**",
              f"- Tests claiming a requirement: "
              f"**{sum(len(v) for v in claimed.values())}**", ""]
    return "\n".join(lines)


def find_problems(analysis: dict[str, list[dict[str, object]]],
                  claimed: dict[str, list[tuple[str, str]]]) -> list[str]:
    """Every way the argument can have a hole. Pure, so it can be tested.

    `tests/test_traceability_gate.py` drives this directly with crafted inputs
    and watches each branch fail, because a gate nobody has seen fail is an
    assumption rather than a control.
    """
    declared = {str(r["id"]) for r in analysis["requirements"]}
    goals = {str(g["id"]) for g in analysis["goals"]}
    hazards = {str(h["id"]) for h in analysis["hazards"]}
    problems: list[str] = []

    # Downward: every requirement must be verified by something.
    for requirement in sorted(declared - set(claimed)):
        problems.append(f"{requirement} is not verified by any test")

    # Upward: every claim must name a requirement that exists. This is the
    # quieter direction. A test claiming SR-O1 for SR-01 runs, passes, and makes
    # the matrix look complete while verifying nothing that was asked for.
    for requirement in sorted(set(claimed) - declared):
        where = ", ".join(f"{f}::{t}" for f, t in claimed[requirement])
        problems.append(f"{requirement} is claimed by {where} but is not a requirement")

    # And the analysis has to hang together: a requirement under a goal that
    # does not exist, or a goal covering a hazard that does not, is a matrix
    # that reads as complete and traces to nothing.
    for requirement in analysis["requirements"]:
        if str(requirement["goal"]) not in goals:
            problems.append(f"{requirement['id']} names goal {requirement['goal']}, "
                            f"which does not exist")
    for goal in analysis["goals"]:
        for hazard in goal["hazards"]:  # type: ignore[attr-defined]
            if str(hazard) not in hazards:
                problems.append(f"{goal['id']} names hazard {hazard}, "
                                f"which does not exist")
    return problems


def main() -> int:
    analysis = load_analysis()
    claimed = collect_claims(TESTS)
    problems = find_problems(analysis, claimed)

    hazards = {str(h["id"]) for h in analysis["hazards"]}
    goals = {str(g["id"]) for g in analysis["goals"]}
    declared = {str(r["id"]) for r in analysis["requirements"]}

    if problems:
        print("The safety argument has gaps:")
        for problem in problems:
            print(f"  {problem}")
        return 1

    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text(build_report(analysis, claimed), encoding="utf-8")
    print(f"traceability complete: {len(hazards)} hazards, {len(goals)} goals, "
          f"{len(declared)} requirements, "
          f"{sum(len(v) for v in claimed.values())} verifying tests")
    return 0


if __name__ == "__main__":
    sys.exit(main())
