"""Play every scenario and write the OEE report.

Regenerated in CI and diffed, like the traceability matrix, because a
performance figure that is only as current as the last time somebody remembered
to rerun it is not a measurement, it is a memory.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from vpc.scenario import SCENARIOS, Result, run  # noqa: E402

REPORT = Path(__file__).resolve().parents[1] / "report" / "oee.md"


def percent(value: float) -> str:
    return f"{value * 100:.1f}%"


def build(results: list[Result]) -> str:
    baseline = results[0]
    lines = [
        "# Scenario runs and OEE",
        "",
        "Generated by `scripts/run_scenarios.py`. Do not edit by hand.",
        "",
        "Each scenario isolates a single loss, so the difference against the",
        "baseline is attributable to one cause. That is what makes these numbers",
        "an argument rather than a statistic: a cell with one OEE figure tells you",
        "how it did, and a cell with three tells you why.",
        "",
        "## Definitions used, because OEE is easy to flatter",
        "",
        "- **Availability** = scans producing / scans planned. The whole run is",
        "  planned time, so a stop and the restart nobody can skip both count",
        "  against it.",
        "- **Performance** = (ideal scans per product x total count) / producing",
        "  scans. **Total** count, not good count: performance asks how fast the",
        "  machine ran and quality asks how much was worth keeping, and merging",
        "  them hides a fast line making scrap.",
        "- **Quality** = good count / total count. Ejected bottles are in the",
        "  denominator. They occupied the stations, consumed the cycle and were",
        "  thrown away, and leaving them out would credit the cell with capacity",
        "  it spent producing waste.",
        "- **Ideal scans per product** is *derived*, not chosen: the filler holds",
        "  a bottle for three scans and the capper for two, so the line cannot",
        f"  beat {baseline.ideal_scans_per_product} scans per product however it is driven.",
        "",
        "## Results",
        "",
        "| Scenario | Availability | Performance | Quality | OEE | vs baseline |",
        "|---|---|---|---|---|---|",
    ]
    for result in results:
        if result is baseline:
            delta = "—"
        else:
            change = (result.oee - baseline.oee) / baseline.oee * 100
            delta = f"{change:+.1f}%"
        lines.append(
            f"| {result.scenario.name} | {percent(result.availability)} | "
            f"{percent(result.performance)} | {percent(result.quality)} | "
            f"**{percent(result.oee)}** | {delta} |")

    lines += ["", "## What each run asked, and what it answered", ""]
    for result in results:
        lines += [
            f"### {result.scenario.name}",
            "",
            f"*{result.scenario.question}*",
            "",
            f"- Producing for **{result.producing_scans}** of "
            f"{result.scans} scans",
            f"- **{result.total_count}** bottles processed: "
            f"{result.produced} good, {result.rejected} scrapped",
            f"- A {percent(result.availability)} / P {percent(result.performance)} "
            f"/ Q {percent(result.quality)} → **OEE {percent(result.oee)}**",
            "",
        ]

    lines += [
        "## The shape of the losses is the finding",
        "",
        "The three runs lose OEE in different factors, and that is the whole point",
        "of splitting it into three:",
        "",
        "- A **guard opening** costs **availability**. The cell is fine; it is not",
        "  allowed to run, and the restart is a deliberate act nobody can skip.",
        "- A **starved infeed** costs **performance**. The cell is running",
        "  perfectly and producing nothing, and a single availability figure would",
        "  have called that a good hour.",
        "",
        "A plant manager who only sees one number cannot tell those apart, and the",
        "remedies are completely different: one is a procedure, the other is a",
        "supplier.",
        "",
        "## Honest limits",
        "",
        "These are simulation scans, not minutes. The plant advances in discrete",
        "steps and the relationship between a scan and a second is a parameter,",
        "so no figure here converts to a rate per hour.",
        "",
        "The quality figure comes from a deterministic every-seventh-bottle defect",
        "rate written into the plant. It measures that the reject path works, not",
        "what a real filler's defect rate would be.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    results = [run(scenario) for scenario in SCENARIOS]
    REPORT.parent.mkdir(exist_ok=True)
    REPORT.write_text(build(results), encoding="utf-8")
    for result in results:
        print(f"{result.scenario.name:22} OEE {percent(result.oee):>6}  "
              f"(A {percent(result.availability)} "
              f"P {percent(result.performance)} "
              f"Q {percent(result.quality)})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
